# Problema 1

La fábrica de bicicletas Expend produce dos modelos de bicicletas, $M$ y $N$. La matriz $A$ nos indica las cantidades de acero y aluminio que requiere cada bicicleta, expresadas en kg según el modelo a producir, mientras que la matriz $B$ nos entrega un reporte de la cantidad de bicicletas producidas de ambos modelos para los dos primeros meses del año pasado.

<br>

\begin{equation*}
\begin{matrix}
& \begin{matrix}
 & \ \ \ \  M & N
\end{matrix}  \\
&A= \begin{pmatrix}
1 & 2 \\
3 & 2 \\
\end{pmatrix} & \ \begin{matrix}
Acero\\
Aluminio
\end{matrix}\\
\end{matrix}
\ \ \ \ \ \ \ \ \ \ \ \ \ \
\begin{matrix}
& \begin{matrix}
& \ \ \ \ \ \ \ ene & feb &
\end{matrix} & \\
&B= \begin{pmatrix}
290 &  312 \\
 345 &  413 \\
\end{pmatrix} & \begin{matrix}
M\\
N
\end{matrix}\\
\end{matrix}
\end{equation*}

<br>

1. Indique el orden de cada matriz. ¿Es posible determinar la multiplicación entre ambas matrices? Justifique.
2. Determine utilizando *Python* la matriz $C = A \cdot B$
3. Indique e interprete el valor de los elementos $c_{21}$ y $c_{11}$.

In [ ]:
#Matriz A= 2x2 y la matriz B = 2x2
#Es posible determinar la multiplicacion de A2x2 * B2x2  ya que la cantidad de columanas de A es igual a la cantidad de filas de B

import numpy as np
A = np.array([[1,2],[3,2]])
B = np.array([[290,312],[345,413]])

C = A.dot(B)
print(C)

#Pregunta3:
c21=C[2-1,1-1]
c11= C[1-1,1-1]
print(f'Se utilizo un total de {c21} Aluminio en los dos modelos el mes enero')

[[ 980 1138]
 [1560 1762]]
Se utilizo un total de 1560 Aluminio en los dos modelos el mes enero


# Problema 2

Una pequeña cadena tiene restaurantes de comida rápida en Santiago, Concepción y Antofagasta, en los que vende hamburguesas, completos y mateadas. En un fin de semana, las cantidades de cada comida según cada sucursal se distribuyeron de acuerdo con la siguiente matriz $V$, donde las filas corresponden a los productos y las columnas a las sucursales, mientras que los precios, en pesos, de cada producto están expresados en la matriz $P$.

<br>

\begin{split}
V &= \begin{pmatrix}
 1300 &  900  &  800  \\
 2100 &  1700 &  1500 \\
 1500 &  1200 &  900  \\
\end{pmatrix}\\
\\
P &= \begin{pmatrix}
 4200 &  1500 & 3200 \\
\end{pmatrix}
\end{split}

<br>

Si $I = P \cdot V$

1. Indique el orden de cada matriz.
2. Determine utilizando *Python* la matriz $I$.
3. Indique e interprete el valor de los elementos $v_{32}$, $p_{12}$ e $i_{13}$.

In [ ]:
#preg 1
#v3x3: filas: productos(H, C , M) ; columnas: sucursales (S, C, A)
#P1x3 filas: Costo unitario ;  columnas: Producotos (H, C, M)
#   Preg 2
import numpy as np
V = np.array([[1300,900,800],[2100,1700,1500],[1500,1200,900]])
P=np.array([[4200,1500,3200]])
I=P.dot(V)
print(I)
#v32 = 1200 fila3: M columna2: suc. conce
#en un finde en la sucursal de conce se venden 1200 malteadas.
#p12
#



[[13410000 10170000  8490000]]


# Problema 3

Una fábrica, para un mismo tipo de artículo eléctrico produce $2$ modelos, $A$ y $B$. Las filas de la matriz $M$, en el orden mencionado, nos muestran la cantidad de transistores y resistores que se requieren por cada artículo, según cada modelo. Por otra parte, las filas de la matriz $Q$ nos reportan las cantidades producidas de cada modelo para las tres primeras semanas del mes pasado.

<br>

\begin{split}
M = \begin{pmatrix}
 9 &  14 \\
 4 &  5  \\
\end{pmatrix} \ \ \ \ \ \ \ \ Q = \begin{pmatrix}
 200 &  240 & 220 \\
 175 &  210 & 215 \\
\end{pmatrix}
\end{split}

<br>

Además, considere las matrices $G = M \cdot Q$ y $H = Q \cdot M$.

1. Indique el orden de $M$ y $Q$.
2. ¿Es posible calcular las matrices $G$ y $H$? Justifique.
3. Determine utilizando *Python* la matriz $G$ e interprete los elementos $g_{23}$  y $g_{12}$.
4. ¿Cuántos resistores se utilizaron durante las tres semanas?

In [13]:
import numpy as np
M = np.array([[9,14],[4,5]])
Q = np.array([[200,240,220],[175,210,215]])
#Pregunta1: orden de M = 2x2 Q = 2x3
#pregunta2:G2x3 = M2x2*Q2x3 es posible porque 
#la cantidad de columna de M es igual a la cantidad de filas de Q

#   H = Q2x3 * M2x2 No es posible ya que la cantidad de columna de Q no es igual de la cantidad de fila que M
#pregunta3 calculandoG, G=M*Q (NO SE HACE)
G = M.dot(Q) #ASI SE MULTIPLICAN MATRICES CON PYTHON
print(f'La matrixg=\n{G}')
g23 = G[2-1,3-1] #fila2 los resistores:  Columna 3 semana 3
print(f'se utilizo en total, {g23} resistores en la semana 3 (En ambos modelos)')
g12 = G[1-1,2-1] #fila1: transisotres; columna 2; semana2
print(f'Se utilizo en total {g12} transistores en la semana 2(En la produccion de ambos modelos)')
#pregunta 4: 
gs3 = np.sum(G,axis=1)# asu tambien, G[1].sum() para sumar elementos de una fila
print(f'En total se utlizaron {gs3[1]} resistores las 3 semanas')

La matrixg=
[[4250 5100 4990]
 [1675 2010 1955]]
se utilizo en total, 1955 resistores en la semana 3 (En ambos modelos)
Se utilizo en total 5100 transistores en la semana 2(En la produccion de ambos modelos)
En total se utlizaron 5640 resistores las 3 semanas


# Problema 4

Una empresa de telecomunicaciones necesita optimizar la distribución de su infraestructura de red en Iquique, Santiago y Concepción. Las columnas de la matriz $R$, en el orden mencionado, representan la cantidad de routers y switches que se deben instalar en cada ciudad. La matriz $C$ muestra el costo de instalación, en pesos, de cada router y switch.

<br>

\begin{split}
R = \begin{pmatrix}
 50 &  70 \\
 80 &  110  \\
 60 &  90  \\
\end{pmatrix} \ \ \ \ \ \ C = \begin{pmatrix}
 80000 \\
 45000 \\
\end{pmatrix}
\end{split}

<br>

1. Calcula utilizando *Python* el costo total de instalación para cada ciudad y almacénalo en la matriz $T$.
2. ¿Cuál es la ciudad que tiene mayor costo de instalación?
3. Si se aplica un descuento del $10\%$ en el costo de instalación de los switches, calcula el nuevo costo total de instalación para cada ciudad.

In [ ]:
import numpy as np
R=np.array([[500,70],[80,110],[60,90]]) #Cuidades x RyS
C=np.array([[80000,45000]])             #RsY      x Costo
T= R.dot(C)                             #Ciudaddes x costo total
print(T) #Santiago es la ciudad con mayor costo de instalacion.


ValueError: shapes (3,2) and (1,2) not aligned: 2 (dim 1) != 1 (dim 0)

# Problema 5

Una empresa de servicios en la nube distribuye datos entre tres *Data Center*. La matriz $D$ muestra el volumen de datos (en terabytes) almacenados en cada *Data Center* durante los tres primeros meses del año. Mientras que la matriz $C$ muestra los costos (en dólares) de almacenamiento por terabyte en cada *Data Center*.

<br>

\begin{equation*}
\begin{matrix}
& \begin{matrix}
& \ \ \ \ \ \ \ DC_{1} &   DC_{2} & DC_{3}&
\end{matrix} & \\
&D = \begin{pmatrix}
100 & 150 & 200 \\
120 & 180 & 220 \\
140 & 210 & 250
\end{pmatrix} & \begin{matrix}
Ene\\
Feb\\
Mar
\end{matrix}
\end{matrix}
\ \ \ \ \ \ \ \ \ \ \ \ \ \
\begin{matrix}
& \begin{matrix}
\   
\end{matrix} & \\
&C = \begin{pmatrix}
50 \\
40 \\
30
\end{pmatrix}  \begin{matrix}
DC_{1}\\
DC_{2}\\
DC_{3}
\end{matrix}\\
\end{matrix}
\end{equation*}

<br>

1. Calcula utilizando *Python* la matriz $T = D \cdot C$.
2. Un trabajador indica que en febrero el costo por almacenamiento fue el más alto, ¿es cierta su afirmación?
3. Debido a la inflación, el costo de almacenamiento por terabyte aumenta en un $2,3\%$. Calcula el nuevo costo total de almacenamiento por mes e interprete cada uno de los elementos de la nueva matriz.

# Problema 6

Una compañía que fabrica un determinado producto, tiene $4$ plantas de producción y $5$ bodegas de almacenamiento. La matriz $T$ muestra las unidades de este producto que se generan mensualmente en la planta $i$ y que son transportadas a la bodega $j$, para quedar almacenadas allí durante el mes en que fueron producidas.

Además, la matriz $C$ detalla, para el primer semestre del presente año, el costo unitario (en dólares) de almacenamiento del producto durante el mes $j$ en la bodega $i$.

<br>

\begin{split}
T = \begin{pmatrix}
 500 &  400  &  300 & 200 & 100 \\
 600 &  500  &  400 & 300 & 200 \\
 700 &  600  &  500 & 400 & 300 \\
 800 &  700  &  600 & 500 & 400 \\
\end{pmatrix} \ \ \ \ \ \ C = \begin{pmatrix}
 5 &  6  &  7 &  8  &  9 & 6 \\
 4 &  5  &  6 &  7  &  8 & 7 \\
 3 &  4  &  5 &  6  &  7 & 9 \\
 2 &  3  &  4 &  5  &  6 & 6 \\
 8 &  5  &  6 &  3  &  7 & 5 \\
\end{pmatrix}
\end{split}

<br>

1. Determina la matriz $G = T \cdot C$.
2. Interpreta los elementos $t_{14}$, $c_{53}$ y $g_{35}$.
3. ¿Cuánto cuesta almacenar una unidad del producto en la bodega $4$ durante marzo de este año?
4. ¿Cuánto dinero gasta la empresa por almacenar la producción mensual de la planta $2$ durante el mes de abril?


# Problema 7

Una empresa dedicada al desarrollo de software, que cuenta con tres sucuersales, necesita renovar los siguientes implementos para su personal: laptop de alto rendimiento, monitor externo de alta resolución, teclado mecánico, mouse ergonómico y disco duro de alta capacidad. Para esto, decide cotizar con tres proveedores y así encontrar el precio más conveniente para realizar la compra. La matriz $F$, en el orden mencionado, indica la cantidad de artículos que necesita comprar para cada sucursal. La matriz $G$ indica el precio unitario (en miles de pesos) de cada producto por proveedor.

<br>

\begin{split}
F = \begin{pmatrix}
 7 &  6  &  15 & 17 & 18 \\
 5 &  10  &  20 & 13 & 12 \\
 8 &  4  &  12 & 18 & 9 \\
\end{pmatrix} \ \ \ \ \ \ G = \begin{pmatrix}
 1700 &  1750 &  1800 \\
  868 &  803  &  840  \\
  165 &  160  &  150  \\
  70  &  73  &   65   \\
  110 &  124  &  115  \\
\end{pmatrix}
\end{split}

<br>

1. Calcula utilizando *Python* la matriz $D = F \cdot G$.
2. Interpreta los elementos $d_{33}$ y $d_{21}$.
3. ¿Cuál es el proveedor más conveniente para realizar todas las compras?
4. Si escoge el proveedor más conveniente, ¿en qué sucursal deberá invertir más dinero por la renovación de los implementos?

In [ ]:
import numpy as np

F= np.array([[7,6,15,17,18],[5,10,20,13,12],[8,4,12,18,9]])
G=np.array([[1700,1750,1800],[868,803,840],[165,160,150],[70,73,65],[110,124,115]])
#F3x5 sucursales x provedores
#G 5x3 implementos x provedores
#D 3x3 sucursal x provedor
D= F.dot(G)
print(f'D; {D}')
d33=D[3-1,3-1]
#filas Scursal3; coluna 3: provedor3 #21765
#la sucrusal3 en el provedor 3 es de 21765 miles de deolares

print(f'{d33}')
d21 = D[2-1,1-1]
#Fila  2: sucursal2 columna 1: proveodr1
# el costo toal de compra todos los implementos de la sucrusal 2 en el provedor 1 es de 22710miles de dolares.
#Preg3

#cual es proveedor más conveniente
#valor total de cada provedor por columna
suma = np.sum(D,axis=0) #sumar los elementos de las columnas
print(suma)
#el proveedor 1 es más conveniente
#Que sucrusal gastará más si se compra al provedor mass conveniente
#la sucursal 1 si le compra al proveedor más conveniente la sucursal que gastará más dinero será la 1



D; [[22753 22941 23065]
 [22710 22417 22625]
 [21302 21562 21765]]
21765
[66765 66920 67455]
<built-in function sum>


# Problema 8

Sea la matriz $A$:

<br>

\begin{split}
A = \begin{pmatrix}
 3 &  1  &  2 \\
 1 &  2  &  1 \\
 4 &  1  &  3 \\
\end{pmatrix}
\end{split}

<br>

1. Calcula, utilizando *Python*, la matriz $A^{-1}$.
2. Calcula la matriz $I = A \cdot A^{-1}$.
3. Calcula la matriz $I^{-1}$. Analiza este resultado, comparando con los resultados obtenidos en los ítems anteriores. ¿Puedes encontrar alguna relación para estas matrices?

In [18]:
A=np.array([[3,1,2],[1,2,1],[4,1,3]]) #A-1 se refiere a la matriz inversa 
A_inv=np.linalg.inv(A) #matriz inversa de A
print(A_inv)
print('------------------------')
#Preg2
I = np.round(A.dot(A_inv),10) #Calculando la matriz identidad
print(I)
print('----------------------------')
A2 = A.dot(I)
#comprobando que al multiplicar la matriz identidad 
# por cualquier matriz, muestra la misma matriz
print(A2)
#pre3
print('---------------------')
I_inv=np.linalg.inv(I)
print(I_inv)

[[ 2.5 -0.5 -1.5]
 [ 0.5  0.5 -0.5]
 [-3.5  0.5  2.5]]
------------------------
[[ 1. -0.  0.]
 [ 0.  1.  0.]
 [ 0. -0.  1.]]
----------------------------
[[3. 1. 2.]
 [1. 2. 1.]
 [4. 1. 3.]]
---------------------
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Problema 9

1. Considera que el siguiente sistema de ecuaciones:

<br>

\begin{split}
2x + y & = 7 \\
3x - 2y & = 21
\end{split}

<br>

$\hspace{1cm}$ Se puede escribir matricialmente como:

<br>

\begin{split}
\begin{pmatrix}
 2  &  1 \\
 3 & -2 \\
\end{pmatrix} \cdot \begin{pmatrix}
 x \\
 y \\
\end{pmatrix} = \begin{pmatrix}
 7 \\
 21 \\
\end{pmatrix}
\end{split}

<br>

* Utiliza la matriz inversa para encontrar los valores de $x$ e $y$ que permiten satisfacer ambas ecuaciones simultáneamente.

<br>

2. Considera que el siguiente sistema de ecuaciones:

<br>

\begin{split}
h + m & = 60 \\
0,16h + 0,2m & = 11
\end{split}

<br>

$\hspace{1cm}$ Se puede escribir matricialmente como:

<br>

\begin{split}
\begin{pmatrix}
 1  &  1 \\
 0,16 & 0,2 \\
\end{pmatrix} \cdot \begin{pmatrix}
 h \\
 m \\
\end{pmatrix} = \begin{pmatrix}
 60 \\
 11 \\
\end{pmatrix}
\end{split}

<br>

* Utiliza la matriz inversa para encontrar los valores de $h$ y $m$ que permiten satisfacer el sistema de ecuaciones.

In [ ]:
A = np.array([[2,1],[3,-2]])
B=np.array([[7],[21]])
A_inv = np.linalg.inv(A)
X = A_inv.dot(B)
print(X)
#Comprobando
B_comp = A.dot(X)
print(B_comp)

[[ 5.]
 [-3.]]
[[ 7.]
 [21.]]


In [22]:
A = np.array([[1,1],[0.16,0.2]])
B=np.array([[60],[11]])
A_inv=np.linalg.inv(A)
H=A_inv.dot(B)
print(H)
#comprobando
B_comp=A.dot(H)
print(B_comp)

[[25.]
 [35.]]
[[60.]
 [11.]]


# Problema 10

Considera los siguientes sistemas de ecuaciones:

<br>

**a)**
\begin{split}
2m + 4p & = 2900 \\
3m + 3p & = 3150
\end{split}
<br>
<br>
**b)**
\begin{split}
n + v & = 160 \\
50n + 300v & = 23000
\end{split}

<br>

1. Escribe ambos sistemas de ecuaciones de forma matricial.
1. Utiliza la matriz inversa para calcular las soluciones de ambos sistemas de ecuaciones.




# Problema 11

Una persona tiene $\$8000$ en monedas de $\$10$ y de $50$. El sistema de ecuaciones que representa la situación es el siguiente:

<br>

\begin{split}
x + y & = 200 \\
10x + 50y & = 8000
\end{split}

<br>

1. ¿Qué representa cada variable?
2. Explica qué representa cada una de las ecuaciones del sistema.
3. ¿Cuántas monedas de $\$10$ y de $\$50$ tiene?

# Problema 12

En una granja hay $132$ animales entre patos y vacas. En total hay $402$ patas. El sistema que modela la situación planteada es:

<br>

\begin{split}
p + v & = 132 \\
2p + 4v & = 402
\end{split}

<br>

1. ¿Qué representan las incógnitas del sistema?
2. ¿Cuántos patos hay?

# Problema 13

Luis compró $5$ cables USB y $6$ pendrives, en total canceló $\$82.890$. Pablo compró a los mismos precios $3$ cables USB y $7$ pendrives, y canceló $\$59.900$.

El sistema que modela el problema es:

<br>

\begin{split}
5x + 6y &= 82890 \\
3x +  7y &= 59900
\end{split}

<br>


1. ¿Qué representa cada incógnita en el contexto del problema?
2. Determina cuánto pagaron por cada cable USB.