In [2]:
import numpy as np
A = np.array([[45,25],[44,14],[36,23],[20,29],[22,37]])
A_T = A.T
print(A_T)

[[45 44 36 20 22]
 [25 14 23 29 37]]


In [3]:
def D(n):
    return 2563*n+12850

print(D(10))

38480


In [6]:
import numpy as np

VI = [6,12,18,24]
VD = [55,100,145,190]
parametros = np.polyfit(VI,VD,1)
m = round(parametros[0],2)
n = round(parametros[1],2)
print(m,n)
def F(x):
    return 7.5*x+10
print(F(12))



7.5 10.0
100.0


In [8]:
def C(h):
    return 60*h+180
print(C(2))

300


In [10]:
def A(n):
    return 2*(n**3) +5
print(A(40))


128005
128005


In [12]:
def A(n):
    return 5*n +5
print(A(11))
import sympy as sp
x = sp.Symbol('x')
ecuacion = A(x)-60
solucion = sp.solve(ecuacion,x)
print(solucion)


60
[11]
60


In [16]:
a_1 =90
d = 30
def A(n):
    return a_1 + (n-1)*d
lista = []
for i in range (1,31):
    lista.append(A(i))
suma = sum(lista)
print(suma)

15750


In [22]:
import numpy as np

A = np.array([[36,56],[12,38]])
B = np.array([[28940],[14480]])

A_inv = np.linalg.inv(A)
Y = A_inv.dot(B)
print(Y)
#Comprobar
print(36 * 415 + 56*250)
print(12 * 415 + 38*250)

[[415.]
 [250.]]
28940
14480
