$$Pregunta1$$

In [3]:
def A(n):
    return 48 + 0.7*n
print(A(15))


58.5


$$Pregunta 2$$


In [1]:
import sympy as sp
def B(n):
    return (n**3)-2*n

print(B(8))

valor =  469
an= 0
i = 0
while an<valor:
    i+=1
    an=B(i)
print(f'La posicion del termino 469 es {i}')


496
La posicion del termino 469 es 8


$$Pregunta 5 $$

In [23]:
def a(n):
    return 900 - (n-1) * 100
print(a(1))

900


$$Pregunta 6$$

In [30]:
a_1 = 6
r = 2
def A(n):
    return a_1*r**(n-1)
print(A(12))

12288


$$Pregunta 9$$

In [31]:
import numpy as np
A = np.array([[-2,5,-1], [-8,4,8]])
A_t = A.T
print(A_t)

[[-2 -8]
 [ 5  4]
 [-1  8]]


$$Pregunta 10$$


In [32]:
A=np.array([[30,50],[25,18], [12,16],[9,40]])
B = np.array([[10,30],[15,27],[24,14],[10,22]])
C = A+B
print(C)

[[40 80]
 [40 45]
 [36 30]
 [19 62]]


$$Pregunta 13$$

In [35]:
print((430*0.30) + 430)

559.0


$$Pregunta 14$$

In [42]:
A = np.array([[700,1400],[1,1]])
B = np.array([[70000],[80]])
A_inv = np.linalg.inv(A)
R = A_inv.dot(B)
print(R)
print(700*60 + 1400*20)
print(60+20)
print(f'La cantidad de conectores R45cat5 que se deben vender para asegurar la rentabilidad mínima es de {R[0][0]}')
print(f'Para los conectores R45cat6 se deben vender {R[1][0]} para asegurar la rentabilidad mínima')

[[60.]
 [20.]]
70000
80
La cantidad de conectores R45cat5 que se deben vender para asegurar la rentabilidad mínima es de 60.0
para los conectores R45cat6 se deben vender 20.0 para asegurar la rentabilidad mínima
