la funcion calcula la variable independente, es decir que el resultado es la variable dependiente


In [ ]:
#La función lineal que permite calcular el tiempo de ejecución de un algoritmo (en milisegundos) según el tamaño de la lista de n elementos, está dada por:
def T(n):
    return 3*n + 5
print(T(101))

308


In [3]:
#El costo de procesamiento (en dólares) en función de las tareas a procesar en un sistema computacional, se puede modelar en la siguiente tabla: 
#La forma algebraica de la función que relaciona ambas variables es:
#anotar las dos variables para polifit resuelva
import numpy as np
VI = [5,10,15,20] # Tienen que ir en la misma posicion, es decir, el 5 va con 200
VD= [200,300,400,500]
parametros = np.polyfit(VI,VD,1)
m = round(parametros[0],2)
n = round(parametros[1],2)
print(m,n)

20.0 100.0


In [ ]:
#Dominio contextualizado son los valoores de la variable independiente en el contexto
# A inicios del año 1985 se funda un club deportivo. Se sabe que después de x años transcurridos desde la fundación del club hasta inicios del año 2013
# el total de integrantes nuevos se puede estimar mediante la función representada en el siguiente gráfico:

In [ ]:
#El tamaño de una base de datos en terabytes (TB) crece exponencialmente en función del tiempo en años, a través del siguiente modelo:
#D left parenthesis t right parenthesis equals 2 times 1 comma 2 to the power of t
#¿Cuántos años deben pasar que la base de datos tenga un tamaño de 20 TB?
def D(t):
    return 2*1.2**(t)
import sympy as sp
x = sp.Symbol('x')
ecuacion = D(x)-20
solucion = sp.solve(ecuacion,x)
print(solucion)
print(D(solucion[0]))
#Esto para resolver una ecuacion.

[12.6292531365133]
20.0000000000000


In [7]:
import numpy as np
e = np.e
def U(t):
    return 1000*e**(0.1*t)
print(U(12))

3320.1169227365476


In [8]:
#Sucesiones:
def A(n):
    return 5*(n**3) - 2*n
print(A(15))

16845


In [ ]:
#Aritmetica tiene diferencia constante
# an=a1+(n-1)*d
a_1= 2.1
d=0.1
def a(n):
    return a_1+(n-1)*d
#forma 1 para encontrar la posicion del termino 5.6
valor = 5.6
an=0
i=0
while an<valor:
    i+=1
    an=a(i)
print(f"La posición del término es {i}")
#compruebe que efectivamente i sea la posición del término:
ai=a(i)
print(f"a_{i}={a(i)}={valor}")
##------------------------- formula 2
x=sp.Symbol("x")
ecuacion= a(x) - 5.6
solucion=sp.solve(ecuacion,x)
print(solucion)





La posición del término es 36
a_36=5.6=5.6
[36.0000000000000]


In [11]:
a_1 = 1000
d=5
def a(n):
    return a_1+(n-1)*d
print(a(25))

1120


In [ ]:
#Geometrica
a_0 = 10
r = 2 # porque habla de duplicarse
a_1 = 10*r
#Formula de geometrica
#a1 *r**(n-1)

In [ ]:
a1=250
d = 50
# an = a1+(n.1)*d
# an = 250(n.1)50

In [13]:
a_1 = 300
d = 40
def A(n):
    return a_1 + (n-1)*d
print(A(8))

580


In [16]:
#para resolver sin saber el 0
a4 = 24
a6= 96
r = (a6/a4)**(1/2) #Raiz cuadrada 6-4 = 2
a9 = a4*r**(5) #5= 9-4
print(a9)
#a9 = a6*r**(3)  9-6 = 3
a1 = a6 * r**(-5)
def a(n):
    return a1*r**(n-1)
print(a(9))




768.0
768.0


In [ ]:
#Matricess
#Incrementa 20%
b32 = 5
b32prima = b32*1.2
print(b32prima)
# o más largo aumentando toda la matriz en 20%



6.0


In [19]:
# A 15x10 filas: Inversionista
#       columnas: tipo Accion
# B 10x5 filas: tipo Accion
#       columnas: Dia habil
# R15x5 si se multiplican R = resultante
# R15x5 Inversionistas x dias
import numpy as np
#Cración de matrices mediante función sobre los índices

A = np.fromfunction(lambda i, j: 20*(i+1)*(j+1), (15,10))
E = np.fromfunction(lambda i, j: 4*(i+1)+(j+1), (10,5))
print(A)
print(E)
#En cuanto está evaluando, para el miercoles de la semana pasasa,
#El total de acciones que posee en esta empresa el inversionista 8
R= A.dot(E)
print(R[8-1,3-1])

[[  20.   40.   60.   80.  100.  120.  140.  160.  180.  200.]
 [  40.   80.  120.  160.  200.  240.  280.  320.  360.  400.]
 [  60.  120.  180.  240.  300.  360.  420.  480.  540.  600.]
 [  80.  160.  240.  320.  400.  480.  560.  640.  720.  800.]
 [ 100.  200.  300.  400.  500.  600.  700.  800.  900. 1000.]
 [ 120.  240.  360.  480.  600.  720.  840.  960. 1080. 1200.]
 [ 140.  280.  420.  560.  700.  840.  980. 1120. 1260. 1400.]
 [ 160.  320.  480.  640.  800.  960. 1120. 1280. 1440. 1600.]
 [ 180.  360.  540.  720.  900. 1080. 1260. 1440. 1620. 1800.]
 [ 200.  400.  600.  800. 1000. 1200. 1400. 1600. 1800. 2000.]
 [ 220.  440.  660.  880. 1100. 1320. 1540. 1760. 1980. 2200.]
 [ 240.  480.  720.  960. 1200. 1440. 1680. 1920. 2160. 2400.]
 [ 260.  520.  780. 1040. 1300. 1560. 1820. 2080. 2340. 2600.]
 [ 280.  560.  840. 1120. 1400. 1680. 1960. 2240. 2520. 2800.]
 [ 300.  600.  900. 1200. 1500. 1800. 2100. 2400. 2700. 3000.]]
[[ 5.  6.  7.  8.  9.]
 [ 9. 10. 11. 12. 13.]
 [13. 14

In [22]:
a = np.array([[4,8],[2,6]])
b= np.array([[72],[40]])
A_inv = np.linalg.inv(a) #AX=B
X = A_inv.dot(b) #inversa de coeficiente por b
print(X)

#comprobar
B_comprobacion = a.dot(X)
print(B_comprobacion)

[[14.]
 [ 2.]]
[[72.]
 [40.]]


In [ ]:
##Correcion de respuesta 580

#En una tienda recién inaugurada, la primera semana ha vendido
# 300 unidades de un producto determinado y se espera 
# que las ventas aumenten en 40 unidades cada semana. 
# ¿Cuántas unidades del producto se proyecta vender en 
# total al cabo de 2 meses? Considere que 1 mes equivale a
#  4 semanas.

a_1 = 300
d = 40
def A(n):
    return a_1 + (n-1)*d
lista = [
]
for i in range(1,9):
    lista.append(A(i))
suma = sum(lista)
print(suma)
#ya que ppiden el total.



3520
